
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicePlusImplService", targetNamespace = "http://beans/", wsdlLocation = "http://localhost:8083/ServicePlusImplService/ServicePlusImpl?wsdl")
public class ServicePlusImplService
    extends Service
{

    private final static URL SERVICEPLUSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEPLUSIMPLSERVICE_EXCEPTION;
    private final static QName SERVICEPLUSIMPLSERVICE_QNAME = new QName("http://beans/", "ServicePlusImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/ServicePlusImplService/ServicePlusImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEPLUSIMPLSERVICE_WSDL_LOCATION = url;
        SERVICEPLUSIMPLSERVICE_EXCEPTION = e;
    }

    public ServicePlusImplService() {
        super(__getWsdlLocation(), SERVICEPLUSIMPLSERVICE_QNAME);
    }

    public ServicePlusImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEPLUSIMPLSERVICE_QNAME, features);
    }

    public ServicePlusImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEPLUSIMPLSERVICE_QNAME);
    }

    public ServicePlusImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEPLUSIMPLSERVICE_QNAME, features);
    }

    public ServicePlusImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicePlusImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicePlusWS
     */
    @WebEndpoint(name = "ServicePlusImplPort")
    public ServicePlusWS getServicePlusImplPort() {
        return super.getPort(new QName("http://beans/", "ServicePlusImplPort"), ServicePlusWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePlusWS
     */
    @WebEndpoint(name = "ServicePlusImplPort")
    public ServicePlusWS getServicePlusImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beans/", "ServicePlusImplPort"), ServicePlusWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEPLUSIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICEPLUSIMPLSERVICE_EXCEPTION;
        }
        return SERVICEPLUSIMPLSERVICE_WSDL_LOCATION;
    }

}
